name: pst11
channels:
  - pytorch
  - conda-forge
  - defaults
  - nvidia
dependencies:
  - cudatoolkit-dev
  - plyfile
  - python=3.11
  - pytorch
  - torchaudio
  - torchvision
  - tqdm
  - pytorch-cuda=12.1
  - wheel
  - tqdm
  - lightning
  - black
  - ruff
  - hydra-core
  - jaxtyping
  - beartype
  - wandb
  - einops
  - colorama
  - scikit-image
  - colorspacious
  - matplotlib
  - moviepy
  - imageio
  - timm
  - dacite
  - lpips
  - e3nn
  - tabulate
  - svg.py

  - pip:
    - git+https://github.com/dcharatan/diff-gaussian-rasterization-modified
    # - submodules/simple-knn