name: pst10
channels:
  - pytorch
  - conda-forge
  - defaults
  - nvidia
dependencies:
  - cudatoolkit=11.6
  - plyfile
  - pip
  - tqdm
  - wheel
  - lightning
  - black
  - ruff
  - hydra-core
  - jaxtyping
  - beartype
  - wandb
  - einops
  - colorama
  - scikit-image
  - colorspacious
  - matplotlib
  - moviepy
  - imageio
  - timm
  - dacite
  - lpips
  - e3nn
  - tabulate
  - svg.py
  - xformers




  - pip:
    - git+https://github.com/dcharatan/diff-gaussian-rasterization-modified